version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/jira
      SPRING_DATASOURCE_USERNAME: jira
      SPRING_DATASOURCE_PASSWORD: JiraRush
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./resources:/opt/jirarush/resources
    depends_on:
      - app
    restart: unless-stopped

  postgres-db:
    image: postgres
    ports:
      - "5432:5432"  # Экспонируем порт для внешнего доступа
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      PGDATA: /var/lib/postgresql/data/pgdata  # Соответствует вашей предыдущей настройке
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Используем ту же папку для volume
    restart: unless-stopped

